[theme]

# Customize theme with 'base'
# base="light"
# base="dark"

# Primary accent for interactive elements
primaryColor = '#f7c04f'

# Background color for the main content area
backgroundColor = '#FAFAFA'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#4f86f7'

# Color used for almost all text
textColor = '#1E1E1E'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font="sans serif"

[deprecation]
showPyplotGlobalUse = false